# Generated by Django 4.2 on 2025-11-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pokemons/'),
        ),
    ]
